# Generated by Django 5.0.4 on 2024-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("auto_update", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=63)),
                ("level", models.CharField(max_length=63)),
                ("form", models.CharField(max_length=63)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
