# Generated by Django 5.0.4 on 2024-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciality",
            name="auto_update",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="speciality",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
