# Generated by Django 5.0.4 on 2024-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="form",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="level",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(max_length=511),
        ),
    ]
