# Generated by Django 5.0.4 on 2024-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialities", "0002_speciality_auto_update_speciality_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="code",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="form",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="level",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
