repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: python -m autoflake
        language: system
        types: [python]
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: python -m isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: python -m flake8
        language: system
        types: [ python ]