# Generated by Django 5.0.4 on 2024-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="auto_update",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="university",
            name="system_guid",
            field=models.CharField(default="_", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
