# Generated by Django 5.0.4 on 2024-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="city",
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name="university",
            name="region",
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name="university",
            name="short_name",
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name="university",
            name="sys_guid",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
