# Generated by Django 4.2.11 on 2024-05-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
