# Generated by Django 4.2.11 on 2024-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_auto_update_university_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='sys_guid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
